ALTER TABLE products ADD COLUMN IF NOT EXISTS sku VARCHAR(255);
ALTER TABLE products ADD COLUMN IF NOT EXISTS ean VARCHAR(255);
ALTER TABLE products ADD COLUMN IF NOT EXISTS stock_quantity INTEGER DEFAULT 0;
ALTER TABLE products ADD COLUMN IF NOT EXISTS is_available BOOLEAN DEFAULT TRUE;
ALTER TABLE products ADD COLUMN IF NOT EXISTS external_pos_id VARCHAR(255);
ALTER TABLE products ADD COLUMN IF NOT EXISTS price NUMERIC;

CREATE TABLE IF NOT EXISTS pos_settings (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  store_id UUID REFERENCES stores(id) ON DELETE CASCADE,
  pos_provider VARCHAR(50) NOT NULL,
  api_token TEXT,
  warehouse_id VARCHAR(255),
  webhook_secret TEXT,
  last_sync_time TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

